spring:
  application:
    name: spring-cloud-eureka
server:
  port: 8001

eureka:
  instance:
    hostname: peer2
  client:
    #register-with-eureka: false
    #fetch-registry: false
    service-url: 
      defaultZone: http://peer1:8000/eureka/,http://peer3:8002/eureka/
      