spring:
  application:
    name: spring-cloud-eureka
server:
  port: 8000

eureka:
  instance:
    hostname: peer1
  client:
    #register-with-eureka: false
    #fetch-registry: false
    service-url: 
      defaultZone: http://peer2:8001/eureka/,http://peer3:8002/eureka/
      