spring:
  application:
    name: spring-cloud-eureka
server:
  port: 8002

eureka:
  instance:
    hostname: peer3
  client:
    #register-with-eureka: false
    #fetch-registry: false
    service-url: 
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/
      