spring:
  application:
    name: spring-cloud-customer
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/
