spring:
  application:
    name: spring-cloud-provider    
server:
  port: 9000
  servlet:
    context-path: /server
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/
